// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxjozccwmckdmqygvljq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4am96Y2N3bWNrZG1xeWd2bGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDg2OTUsImV4cCI6MjA1ODQ4NDY5NX0.8DOAFi2dNLBVtqA4iyvb0ixGIZslnPVaFOgtFeldi5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);